#!/bin/bash

PREFIXES=`cat aggregatedPrefixes.txt | cut -d" " -f2 | grep "\."`
IP_LIST_FILE=ipList.txt
PREFIX_FILE=prefixList.txt
DEBUG_FILE=debug
SCAMPY_OUTPUT=pingResults
if [ ! -e iplist.txt ]; then
   touch prefixList.txt;
fi

echo ${PREFIXES[*]} > $PREFIX_FILE

#./createiplist.py < prefixList.txt > ipList.txt
echo "10.0.0.0/23" | ./createiplist.py > $IP_LIST_FILE
date
scamper -c "ping -P udp" -d $DEBUG_FILE -o $SCAMPY_OUTPUT -f $IP_LIST_FILE -O warts
date
# About 8 min for a /24 network 
